name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  ## Changes

  $CHANGES
categories:
  - title: "Features"
    labels:
      - enhancement
      - feat
  - title: "Bug Fixes"
    labels:
      - bug
      - fix
  - title: "Documentation"
    labels:
      - documentation
      - docs
  - title: "Maintenance"
    labels:
      - chore
      - dependencies
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch
