run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - goimports
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - whitespace
  disable:
    - gosec

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
