name: labels

on:
  push:
    branches: [main, master]
    paths:
      - .github/labels.yml
  workflow_dispatch:

permissions: read-all

jobs:
  sync:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: micnncim/action-label-syncer@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          dry-run: false
          manifest: .github/labels.yml
